import { useEffect, useState } from 'react';
import type { AuditDiff, AuditSnapshotMetadata, ProjectAuditSnapshot } from '@shared/audit';

export function AuditHistory({ audit, onRefreshAudit }: { audit: ProjectAuditSnapshot | null; onRefreshAudit: () => void }) {
  const [history, setHistory] = useState<AuditSnapshotMetadata[]>([]);
  const [diff, setDiff] = useState<AuditDiff | null>(null);
  const [message, setMessage] = useState('');
  const load = () => window.forgeLoopAudit.listAuditHistory().then(setHistory).catch((error) => setMessage(error instanceof Error ? error.message : 'History unavailable.'));
  useEffect(() => { load(); }, []);
  const save = async () => { try { await window.forgeLoopAudit.saveAuditBaseline(); setMessage('Baseline saved.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save baseline.'); } };
  const compare = async (baseAuditId: string) => { try { setDiff(await window.forgeLoopAudit.compareAudits(baseAuditId)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to compare audits.'); } };
  return <div className="space-y-5 animate-fade-in"><div className="flex items-center justify-between gap-3"><div><h1 className="text-xl font-semibold text-forge-text-primary">Audit History</h1><p className="text-sm text-forge-text-muted mt-1">Manual snapshots are stored in application data, outside the audited project.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={load}>Refresh</button><button className="btn-primary" onClick={save}>Save baseline</button></div></div>{message && <p className="text-sm text-forge-text-secondary">{message}</p>}<div className="bg-forge-primary-surface border border-forge-border-subtle rounded-10 overflow-hidden"><div className="divide-y divide-forge-border-subtle/50">{history.length === 0 ? <p className="p-6 text-sm text-forge-text-muted">No saved audit snapshots.</p> : history.map((entry) => <div key={entry.auditId} className="p-4 flex flex-wrap items-center gap-3"><span className="font-mono text-xs text-forge-text-primary">{entry.auditId}</span><span className="text-xs text-forge-text-muted">{entry.generatedAt}</span><span className="text-xs text-forge-text-secondary">{entry.verdict.integrity} · {entry.coveragePercent}% coverage</span><button className="btn-secondary text-xs ml-auto" onClick={() => compare(entry.auditId)}>Compare with current</button></div>)}</div></div>{diff && <div className="bg-forge-primary-surface border border-forge-border-subtle rounded-10 p-5"><h2 className="font-semibold text-forge-text-primary">Changes since baseline</h2><p className="mt-2 text-sm text-forge-text-secondary">{diff.newFindings.length} new · {diff.resolvedFindings.length} resolved · {diff.persistentFindings.length} persistent · score delta {diff.scoreDelta ?? 'unavailable'}</p></div>}{!audit && <button className="btn-secondary" onClick={onRefreshAudit}>Run current audit</button>}</div>;
}
