import { useEffect, useState } from 'react';
import type { StructuralQualityAuditView } from '@shared/audit';
import type { ProjectSnapshot } from '@shared/domain';
import { StatusBadge } from '../components/ui/StatusBadge';

export function Quality({ snapshot, selectedTaskId, onSelectedTaskChange }: { snapshot: ProjectSnapshot; selectedTaskId?: string | null; onSelectedTaskChange: (taskId: string) => void }) {
  const task = snapshot.tasks.find((entry) => entry.taskId === selectedTaskId) ?? snapshot.tasks[0];
  const taskId = task?.taskId;
  const [quality, setQuality] = useState<StructuralQualityAuditView | null>(null);
  useEffect(() => { let cancelled = false; if (!taskId) { setQuality(null); return () => { cancelled = true; }; } window.forgeLoopAudit.getTaskStructuralQuality(taskId).then((value) => { if (!cancelled) setQuality(value); }).catch(() => { if (!cancelled) setQuality(null); }); return () => { cancelled = true; }; }, [taskId]);
  if (!task) return <div className="empty-state"><p className="empty-state-title">No tasks available</p></div>;
  return <div className="space-y-5 animate-fade-in"><div className="flex items-center justify-between gap-3"><div><h1 className="text-xl font-semibold text-forge-text-primary">Engineering Quality</h1><p className="text-sm text-forge-text-muted mt-1">Canonical Structural Quality projection; ForgeLoopAudit never runs a provider.</p></div><select className="input w-48" value={task.taskId} onChange={(event) => onSelectedTaskChange(event.target.value)}>{snapshot.tasks.map((entry) => <option key={entry.taskId} value={entry.taskId}>{entry.taskId}</option>)}</select></div>{!quality || !quality.available ? <div className="bg-forge-warning/10 border border-forge-warning/30 rounded-10 p-5"><p className="font-medium text-forge-warning">Structural quality unavailable</p><p className="mt-1 text-sm text-forge-text-secondary">{quality?.error?.message ?? 'The bundled ForgeLoop capability does not advertise this canonical resource.'}</p><p className="mt-3 text-xs text-forge-text-muted">No local provider was invoked. Audit coverage remains reduced.</p></div> : <div className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="bg-forge-primary-surface border border-forge-border-subtle rounded-10 p-4"><p className="text-xs text-forge-text-muted">Mode</p><p className="mt-2 font-mono text-forge-text-primary">{quality.mode}</p></div><div className="bg-forge-primary-surface border border-forge-border-subtle rounded-10 p-4"><p className="text-xs text-forge-text-muted">Provider</p><p className="mt-2 font-mono text-forge-text-primary">{quality.provider ?? 'None reported'}</p></div><div className="bg-forge-primary-surface border border-forge-border-subtle rounded-10 p-4"><p className="text-xs text-forge-text-muted">Current status</p><div className="mt-2"><StatusBadge status={quality.current.status} size="md" /></div></div></div><div className="bg-forge-primary-surface border border-forge-border-subtle rounded-10 p-5 grid grid-cols-1 md:grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-forge-text-muted">Quality signal</p><p className="mt-1 text-forge-text-primary">{quality.current.qualitySignal ?? 'Not observed'}</p></div><div><p className="text-xs text-forge-text-muted">Delta</p><p className="mt-1 text-forge-text-primary">{quality.current.delta ?? 'Not comparable'}</p></div><div><p className="text-xs text-forge-text-muted">Bottleneck</p><p className="mt-1 text-forge-text-primary">{quality.current.bottleneck ?? 'None reported'}</p></div><div><p className="text-xs text-forge-text-muted">Completion required</p><p className="mt-1 text-forge-text-primary">{quality.completionRequired ? 'Yes' : 'No'}</p></div></div></div>}</div>;
}
